{
 "title": "Network Participation",
 "panels": [
  {
   "type": "text",
   "description": "Network participation metrics",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Network Participation Metrics"
   }
  },
  {
   "title": "Network Data Transfer",
   "type": "timeseries",
   "description": "Data transfer volumes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "libp2p_data_transfer_bytes_total{protocol=~\"global.*\"}",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Topic Peer Count",
   "type": "timeseries",
   "description": "Peer count for each topic",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "gossipsub_topic_peer_count", "legendFormat": "{{topicStr}}" }
   ]
  },
  {
   "title": "DHT Routing Table Size",
   "type": "stat",
   "description": "DHT routing table size indicates how well the keeper is connected to the network",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_kad_dht_routing_table_size"
    }
   ]
  },
  {
   "title": "Connected Peers by Protocol",
   "type": "stat",
   "description": "P2P connection status",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gossipsub_peers_per_protocol_count",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Outbound RPC Requests",
   "type": "timeseries",
   "description": "RPC requests to other nodes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "libp2p_kad_dht_outbound_rpc_requests_total",
     "legendFormat": "{{libp2p_kad_dht_outbound_rpc_requests_total}}"
    }
   ]
  },
  {
   "title": "Message Publishing Activity",
   "type": "timeseries",
   "description": "Messages published and forwarded",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "gossipsub_msg_publish_count_total",
     "legendFormat": "Published - {{topic}}"
    },
    {
     "expr": "gossipsub_msg_forward_count_total",
     "legendFormat": "Forwarded - {{topic}}"
    }
   ]
  }
 ]
}